<?php
	require_once(CLASS_GENERAL_INTERFACE);
	require_once(CLASS_ANTISPAM);
	require_once(CLASS_FIREWALL);
	require_once(CLASS_MODEL);
	require_once(CLASS_APPLICATION);
	require_once(CLASS_LANG);
	require_once(CLASS_ROUTER);
	require_once(CLASS_PLUGIN);
	require_once(CLASS_RUBRIQUE);
	require_once(CLASS_CONFIG);
	require_once(CLASS_LOG);
	require_once(CLASS_EXCEPTION);
	require_once(CLASS_CACHE);
	require_once(CLASS_TEMPLATE);
	require_once(CLASS_APPDEVGC);
	require_once(CLASS_TERMINAL);
	require_once(CLASS_INSTALL);